purchase_type: on_demand
subnet_id: subnet-095e1a2f56490b6a9  
num_instances: 3
key_name: sio-IAM-keypair 
security_group_ids: sg-0dd8b77884feb9eea
instance_type: m4.large
tag_name: kafka-cluster
vol_size: 100
role: worker
use_eips: true
