purchase_type: on_demand
subnet_id: subnet-095e1a2f56490b6a9
num_instances: 1
key_name: sio-IAM-keypair 
security_group_ids: sg-0dd8b77884feb9eea
instance_type: m4.large
tag_name: zoo-cluster
vol_size: 100
role: master
use_eips: true
